# Jekyll config
safe: true
lsi: false
permalink: /:year/:title
paginate: 15
exclude: [ newpost.sh, notes.mdown ]

# site-wide variables
name: Smallblog
url: http://smallblog.desandro.com
css_version: '03'